name: "Get the default bucket name for artifacts"
description: "Works on Unix and Windows-WSL"
inputs:
  bucket:
    description: |
      "Handy parameter. Returns the same value if non-empty.
      Leave empty to use the implicit 'gh-runs_<org-name>_<repo-name>'. 
      For the implicit bucket name, dots are replaced by hyphens, slashes are replaced by underscores. The bucket name should be lowercase. For 'My-Dear-Org/my.repo', we get 'gh-runs_my-dear-org_my-repo'"
    required: false
  __win_shell:
    description: "[Internal] Use a different bash shell command for windows. Uses WSL bash by default"
    default: wsl bash --noprofile --norc -euo pipefail "$(s="$(wslpath '{0}')" && sed -i 's/\r$//' "$s" && echo "$s")"

outputs:
  bucket_name: 
    description: "The default bucket name, based on run id and repo url"
    # Fun hack until we find a proper way: since only one of them will be executed, joining them gives us the correct result!
    value: ${{ steps.bucket_namer_unix.outputs.value }}${{ steps.bucket_namer_win.outputs.value }}

runs:
  using: "composite"
  steps: 
      # Note: code duplication was the only way atm

      - name: Get bucket name [UNIX]
        id: bucket_namer_unix
        if: runner.os != 'Windows'
        shell: bash
        run: |
          s="${{ github.action_path }}/out_bucketname.sh"
          chmod +x "$s"
          "$s" "${{ github.repository }}" "${{ inputs.bucket }}"

      # Can also use this, but it's kinda heavy, so expecting the machine to alraedy have wsl installed
      # - uses: Vampire/setup-wsl@v1
      #   with:
      #       distribution: Ubuntu-20.04

      - name: Get bucket name [WIN-WSL]
        id: bucket_namer_win
        if: runner.os == 'Windows'
        shell: ${{ inputs.__win_shell }}
        run: |
          s=$(wslpath "${{ github.action_path }}/out_bucketname.sh")
          chmod +x "$s"
          "$s" "${{ github.repository }}" "${{ inputs.bucket }}"
